Fix typo and improve build script to detect and use version.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -4,7 +4,7 @@ OMNIBUS_BRANCH="wip" # Branch of dd-agent-omnibus repo to use, default "master"
 USE_ROOT_SUPERVISOR="yes"
 AGENT_VERSION="5.4.5" # default to the latest tag on that branch
 #LOG_LEVEL="debug" # default to "info"
-LOCAL_AGENT_REPO="~/dd-agent" # Path to a local repo of the agent to build from. Defaut is not set and the build will be done against the github repo
+#LOCAL_AGENT_REPO="~/dd-agent" # Path to a local repo of the agent to build from. Defaut is not set and the build will be done against the github repo
 
 mkdir -p pkg
 mkdir -p "cache/$PLATFORM"
@@ -26,11 +26,23 @@ if [ ! -f ~/eos/usr/bin/swix ]; then
 fi
 
 # XXX: find a way to extract file name
-#export FILE=`find ~/pkg -type f -printf "%f\n"`
-export FILE='datadog-agent-0.0.0-1.i686.rpm'
-sudo cp ~/pkg/$FILE ~/eos
-sudo chroot ~/eos /usr/bin/swix create --force datadog-agent.swix $FILE
-sudo rm -rf  ~/eos/*.rpm
-sudo rm -rf  ~/pkg/*
-s3cmd -c ~/dd-agent-omnibus/.s3cfg put eos/datadog-agent.swix s3://fastly-files/private/swix/
-sudo rm -rf  ~/eos/*.swix
+export FILE=`find ~/pkg -type f -name *.rpm -printf "%f\n"`
+#export FILE='datadog-agent-0.0.0-1.i686.rpm'
+
+if [ -f ~/pkg/$FILE ]; then
+	echo "Found ~/pkg/$FILE"
+	sudo cp ~/pkg/$FILE ~/eos
+	echo "Creating swix"
+	sudo chroot ~/eos /usr/bin/swix create --force datadog-agent.swix $FILE
+	echo "Uploading to S3"
+	s3cmd -c ~/dd-agent-omnibus/.s3cfg put eos/datadog-agent.swix s3://fastly-files/private/swix/
+
+  # cleaning up
+	echo "Removing all build artifacts"
+	sudo rm -rf  ~/eos/*.rpm
+	sudo rm -rf  ~/pkg/*
+	sudo rm -rf  ~/eos/*.swix
+else
+  echo "File not found. Exiting"
+  exit 1
+fi
